"""model_correct_1

Revision ID: 0194f40f3c3a
Revises: a934353c8990
Create Date: 2025-09-05 23:26:39.926057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0194f40f3c3a'
down_revision: Union[str, Sequence[str], None] = 'a934353c8990'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('esm_ordered_items_order_id_key'), 'esm_ordered_items', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('esm_ordered_items_order_id_key'), 'esm_ordered_items', ['order_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
