"""add_relation

Revision ID: 2ae32073d229
Revises: 
Create Date: 2025-08-31 21:32:31.891155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ae32073d229'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('esm_ordered_items', sa.Column('item_id', sa.Text(), nullable=False))
    op.create_foreign_key(None, 'esm_ordered_items', 'esm_inventory', ['item_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'esm_ordered_items', type_='foreignkey')
    op.drop_column('esm_ordered_items', 'item_id')
    # ### end Alembic commands ###
