"""user_model_fixed

Revision ID: a1ff519c8e00
Revises: a473b2cceb85
Create Date: 2025-08-31 18:27:48.364571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1ff519c8e00'
down_revision: Union[str, Sequence[str], None] = 'a473b2cceb85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('esm_users', sa.Column('password', sa.String(), nullable=False))
    op.drop_constraint(op.f('esm_users_passsword_key'), 'esm_users', type_='unique')
    op.create_unique_constraint(None, 'esm_users', ['password'])
    op.drop_column('esm_users', 'passsword')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('esm_users', sa.Column('passsword', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'esm_users', type_='unique')
    op.create_unique_constraint(op.f('esm_users_passsword_key'), 'esm_users', ['passsword'], postgresql_nulls_not_distinct=False)
    op.drop_column('esm_users', 'password')
    # ### end Alembic commands ###
