"""model_correct_2

Revision ID: a4fb2123a0bc
Revises: 0194f40f3c3a
Create Date: 2025-09-05 23:55:28.278591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4fb2123a0bc'
down_revision: Union[str, Sequence[str], None] = '0194f40f3c3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('esm_orders', sa.Column('user_id', sa.Text(), nullable=False))
    op.create_foreign_key(None, 'esm_orders', 'esm_users', ['user_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'esm_orders', type_='foreignkey')
    op.drop_column('esm_orders', 'user_id')
    # ### end Alembic commands ###
