"""add_cart_table

Revision ID: bf20b5e69a8c
Revises: d1a49851dace
Create Date: 2025-09-06 14:30:36.690165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf20b5e69a8c'
down_revision: Union[str, Sequence[str], None] = 'd1a49851dace'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('esm_carts',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['esm_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('esm_ordered_items', sa.Column('current_price', sa.Float(), nullable=False))
    op.add_column('esm_ordered_items', sa.Column('cart_id', sa.Text(), nullable=False))
    op.alter_column('esm_ordered_items', 'order_qty',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('uq_order_item'), 'esm_ordered_items', type_='unique')
    op.create_unique_constraint('uq_order_item', 'esm_ordered_items', ['cart_id', 'item_id'])
    op.drop_constraint(op.f('esm_ordered_items_order_id_fkey'), 'esm_ordered_items', type_='foreignkey')
    op.create_foreign_key(None, 'esm_ordered_items', 'esm_carts', ['cart_id'], ['id'], ondelete='CASCADE')
    op.drop_column('esm_ordered_items', 'order_id')
    op.add_column('esm_orders', sa.Column('cart_id', sa.Text(), nullable=False))
    op.create_unique_constraint(None, 'esm_orders', ['cart_id'])
    op.create_foreign_key(None, 'esm_orders', 'esm_carts', ['cart_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'esm_orders', type_='foreignkey')
    op.drop_constraint(None, 'esm_orders', type_='unique')
    op.drop_column('esm_orders', 'cart_id')
    op.add_column('esm_ordered_items', sa.Column('order_id', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'esm_ordered_items', type_='foreignkey')
    op.create_foreign_key(op.f('esm_ordered_items_order_id_fkey'), 'esm_ordered_items', 'esm_orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_order_item', 'esm_ordered_items', type_='unique')
    op.create_unique_constraint(op.f('uq_order_item'), 'esm_ordered_items', ['order_id', 'item_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('esm_ordered_items', 'order_qty',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('esm_ordered_items', 'cart_id')
    op.drop_column('esm_ordered_items', 'current_price')
    op.drop_table('esm_carts')
    # ### end Alembic commands ###
