"""model_correct_3

Revision ID: d1a49851dace
Revises: a4fb2123a0bc
Create Date: 2025-09-05 23:59:20.547020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1a49851dace'
down_revision: Union[str, Sequence[str], None] = 'a4fb2123a0bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('esm_users_password_key'), 'esm_users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('esm_users_password_key'), 'esm_users', ['password'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
